trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarQubePrepare@4
  displayName: Prepare Analysis Configuration task
  inputs:
    SonarQube: 'Sonar-aws'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectVersion=1.0.0.0
      sonar.projectName=springsonarqube
      sonar.sources=src/main/java/
      sonar.language=java
      sonar.sourceEncoding=UTF-8
  enabled: true


- task: Maven@3
  inputs:
    mavenPomFile: '$(Build.SourcesDirectory)/sonarqube/sonarqubespring/pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'pom'
  enabled: true

 
- task: SonarQubePublish@4
  displayName: Publish Quality Gate Result
  inputs:
    pollingTimeoutSec: '300'
  enabled: true
